import jsPDF from 'jspdf'
import { ContractSourceInfo } from '../services/etherscan'
import { AuditResult } from '../services/llm-audit'

export function generateMarkdownReport(
  contractInfo: ContractSourceInfo,
  auditResult: AuditResult,
  contractAddress: string
): string {
  const timestamp = new Date().toLocaleString()
  
  let markdown = `# Smart Contract Security Audit Report\n\n`
  markdown += `**Contract Address:** \`${contractAddress}\`\n`
  markdown += `**Contract Name:** ${contractInfo.contractName}\n`
  markdown += `**Compiler Version:** ${contractInfo.compilerVersion}\n`
  markdown += `**Optimization Enabled:** ${contractInfo.optimizationUsed ? 'Yes' : 'No'}\n`
  markdown += `**Report Generated:** ${timestamp}\n\n`

  // Executive Summary
  markdown += `## Executive Summary\n\n`
  markdown += `${auditResult.executiveSummary}\n\n`

  // Security Overview
  markdown += `## Security Overview\n\n`
  markdown += `| Severity | Count |\n`
  markdown += `|----------|-------|\n`
  markdown += `| Critical | ${auditResult.criticalVulnerabilities.length} |\n`
  markdown += `| Medium   | ${auditResult.mediumSeverityIssues.length} |\n`
  markdown += `| Low      | ${auditResult.lowSeverityIssues.length} |\n\n`

  // Critical Vulnerabilities
  if (auditResult.criticalVulnerabilities.length > 0) {
    markdown += `## 🔴 Critical Vulnerabilities\n\n`
    auditResult.criticalVulnerabilities.forEach((vuln, index) => {
      markdown += `### ${index + 1}. ${vuln.title}\n\n`
      markdown += `**Severity:** ${vuln.severity}\n\n`
      markdown += `**Description:** ${vuln.description}\n\n`
      if (vuln.location) {
        markdown += `**Location:** \`${vuln.location}\`\n\n`
      }
      markdown += `**Impact:** ${vuln.impact}\n\n`
      markdown += `**Recommendation:** ${vuln.recommendation}\n\n`
      markdown += `---\n\n`
    })
  }

  // Medium Severity Issues
  if (auditResult.mediumSeverityIssues.length > 0) {
    markdown += `## 🟡 Medium Severity Issues\n\n`
    auditResult.mediumSeverityIssues.forEach((vuln, index) => {
      markdown += `### ${index + 1}. ${vuln.title}\n\n`
      markdown += `**Severity:** ${vuln.severity}\n\n`
      markdown += `**Description:** ${vuln.description}\n\n`
      if (vuln.location) {
        markdown += `**Location:** \`${vuln.location}\`\n\n`
      }
      markdown += `**Impact:** ${vuln.impact}\n\n`
      markdown += `**Recommendation:** ${vuln.recommendation}\n\n`
      markdown += `---\n\n`
    })
  }

  // Low Severity Issues
  if (auditResult.lowSeverityIssues.length > 0) {
    markdown += `## 🟢 Low Severity Issues\n\n`
    auditResult.lowSeverityIssues.forEach((vuln, index) => {
      markdown += `### ${index + 1}. ${vuln.title}\n\n`
      markdown += `**Severity:** ${vuln.severity}\n\n`
      markdown += `**Description:** ${vuln.description}\n\n`
      if (vuln.location) {
        markdown += `**Location:** \`${vuln.location}\`\n\n`
      }
      markdown += `**Impact:** ${vuln.impact}\n\n`
      markdown += `**Recommendation:** ${vuln.recommendation}\n\n`
      markdown += `---\n\n`
    })
  }

  // Gas Optimizations
  if (auditResult.gasOptimizations.length > 0) {
    markdown += `## ⚡ Gas Optimizations\n\n`
    auditResult.gasOptimizations.forEach((optimization, index) => {
      markdown += `${index + 1}. ${optimization}\n`
    })
    markdown += `\n`
  }

  // Code Quality Assessment
  markdown += `## 📊 Code Quality Assessment\n\n`
  markdown += `${auditResult.codeQualityAssessment}\n\n`

  // Recommendations
  if (auditResult.recommendations.length > 0) {
    markdown += `## 💡 General Recommendations\n\n`
    auditResult.recommendations.forEach((recommendation, index) => {
      markdown += `${index + 1}. ${recommendation}\n`
    })
    markdown += `\n`
  }

  // Footer
  markdown += `---\n\n`
  markdown += `**Disclaimer:** This audit report is generated by AI and should be used as a starting point for security analysis. It is recommended to have the contract reviewed by professional security auditors before deployment.\n\n`
  markdown += `**Report generated by Smart Contract Auditor** - ${timestamp}`

  return markdown
}

export function downloadMarkdown(
  contractInfo: ContractSourceInfo,
  auditResult: AuditResult,
  contractAddress: string
) {
  const markdown = generateMarkdownReport(contractInfo, auditResult, contractAddress)
  const blob = new Blob([markdown], { type: 'text/markdown' })
  const url = URL.createObjectURL(blob)
  
  const link = document.createElement('a')
  link.href = url
  link.download = `audit-report-${contractInfo.contractName}-${Date.now()}.md`
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

export function generatePDF(
  contractInfo: ContractSourceInfo,
  auditResult: AuditResult,
  contractAddress: string
) {
  const pdf = new jsPDF()
  const pageWidth = pdf.internal.pageSize.getWidth()
  const margin = 20
  const maxWidth = pageWidth - (margin * 2)
  let currentY = margin

  // Helper function to add text with word wrapping
  const addText = (text: string, fontSize = 12, isBold = false) => {
    pdf.setFontSize(fontSize)
    if (isBold) {
      pdf.setFont('helvetica', 'bold')
    } else {
      pdf.setFont('helvetica', 'normal')
    }
    
    const lines = pdf.splitTextToSize(text, maxWidth)
    
    // Check if we need a new page
    if (currentY + (lines.length * fontSize * 0.35) > pdf.internal.pageSize.getHeight() - margin) {
      pdf.addPage()
      currentY = margin
    }
    
    pdf.text(lines, margin, currentY)
    currentY += lines.length * fontSize * 0.35 + 5
  }

  // Title
  addText('Smart Contract Security Audit Report', 20, true)
  currentY += 10

  // Contract info
  addText(`Contract Address: ${contractAddress}`, 12, true)
  addText(`Contract Name: ${contractInfo.contractName}`)
  addText(`Compiler Version: ${contractInfo.compilerVersion}`)
  addText(`Optimization Enabled: ${contractInfo.optimizationUsed ? 'Yes' : 'No'}`)
  addText(`Report Generated: ${new Date().toLocaleString()}`)
  currentY += 10

  // Executive Summary
  addText('Executive Summary', 16, true)
  addText(auditResult.executiveSummary)
  currentY += 10

  // Security Overview
  addText('Security Overview', 16, true)
  addText(`Critical Issues: ${auditResult.criticalVulnerabilities.length}`, 12, true)
  addText(`Medium Issues: ${auditResult.mediumSeverityIssues.length}`, 12, true)
  addText(`Low Issues: ${auditResult.lowSeverityIssues.length}`, 12, true)
  currentY += 10

  // Critical Vulnerabilities
  if (auditResult.criticalVulnerabilities.length > 0) {
    addText('Critical Vulnerabilities', 16, true)
    auditResult.criticalVulnerabilities.forEach((vuln, index) => {
      addText(`${index + 1}. ${vuln.title}`, 14, true)
      addText(`Description: ${vuln.description}`)
      if (vuln.location) {
        addText(`Location: ${vuln.location}`)
      }
      addText(`Impact: ${vuln.impact}`)
      addText(`Recommendation: ${vuln.recommendation}`)
      currentY += 5
    })
  }

  // Medium Issues
  if (auditResult.mediumSeverityIssues.length > 0) {
    addText('Medium Severity Issues', 16, true)
    auditResult.mediumSeverityIssues.forEach((vuln, index) => {
      addText(`${index + 1}. ${vuln.title}`, 14, true)
      addText(`Description: ${vuln.description}`)
      if (vuln.location) {
        addText(`Location: ${vuln.location}`)
      }
      addText(`Impact: ${vuln.impact}`)
      addText(`Recommendation: ${vuln.recommendation}`)
      currentY += 5
    })
  }

  // Low Issues
  if (auditResult.lowSeverityIssues.length > 0) {
    addText('Low Severity Issues', 16, true)
    auditResult.lowSeverityIssues.forEach((vuln, index) => {
      addText(`${index + 1}. ${vuln.title}`, 14, true)
      addText(`Description: ${vuln.description}`)
      if (vuln.location) {
        addText(`Location: ${vuln.location}`)
      }
      addText(`Impact: ${vuln.impact}`)
      addText(`Recommendation: ${vuln.recommendation}`)
      currentY += 5
    })
  }

  // Gas Optimizations
  if (auditResult.gasOptimizations.length > 0) {
    addText('Gas Optimizations', 16, true)
    auditResult.gasOptimizations.forEach((optimization, index) => {
      addText(`${index + 1}. ${optimization}`)
    })
    currentY += 10
  }

  // Code Quality Assessment
  addText('Code Quality Assessment', 16, true)
  addText(auditResult.codeQualityAssessment)
  currentY += 10

  // Recommendations
  if (auditResult.recommendations.length > 0) {
    addText('General Recommendations', 16, true)
    auditResult.recommendations.forEach((recommendation, index) => {
      addText(`${index + 1}. ${recommendation}`)
    })
  }

  // Download the PDF
  pdf.save(`audit-report-${contractInfo.contractName}-${Date.now()}.pdf`)
}